**Numpy**

In [1]:
import numpy as np

In [12]:
a=[1,2,3,4]
a1=[5,6,7,8]
b = np.array([5,6,7,8])
b1= np.array([5,6,7,8])

In [13]:
a+b

array([ 6,  8, 10, 12])

In [14]:
a+a1

[1, 2, 3, 4, 5, 6, 7, 8]

In [15]:
b+b1

array([10, 12, 14, 16])

**o d**

In [16]:
b = np.array([24,15,45])

In [17]:
b

array([24, 15, 45])

In [18]:
print(type(b))

<class 'numpy.ndarray'>


In [19]:
b.shape

(3,)

In [20]:
b.ndim

1

In [21]:
b.sum()

np.int64(84)

In [25]:
i=np.array(8)
i

array(8)

In [26]:
i.shape

()

In [27]:
i.ndim

0

**1 dimension**

In [28]:
i = np.array([4,5,6,7,8])

In [29]:
i

array([4, 5, 6, 7, 8])

In [30]:
i.shape

(5,)

In [31]:
i.ndim

1

**2 dimension**

In [32]:
h=np.array([[1,2],[3,4]])

In [33]:
h

array([[1, 2],
       [3, 4]])

In [34]:
h.shape

(2, 2)

In [35]:
h.ndim

2

**3 dimension**

In [36]:
g=np.array([[[1,2],[1,2]]])

In [37]:
g

array([[[1, 2],
        [1, 2]]])

In [38]:
g.shape

(1, 2, 2)

In [39]:
g.ndim

3

**4 dimension**

In [54]:
f = np.array([[[[5,4],[6,6]]]])

In [55]:
f

array([[[[5, 4],
         [6, 6]]]])

In [56]:
f.shape

(1, 1, 2, 2)

In [57]:
f.ndim

4

**5 dimension**

In [60]:
aa=np.array([[[[[1,2],[1,2]]]]])

In [62]:
aa

array([[[[[1, 2],
          [1, 2]]]]])

In [63]:
aa.shape

(1, 1, 1, 2, 2)

In [64]:
aa.ndim

5